import smtplib
import os
import socket
import time  # 新增：用于重试间隔

import ssl
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


def send_gmail_notification(content: str):
    """
    Sends an email notification via Google SMTP with retry logic.
    Requires EMAIL_SENDER and EMAIL_PASSWORD (App Password) in .env.
    """
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")  # Use Gmail App Password
    receiver = "longsizhuo@gmail.com"

    if not sender or not password:
        print("⚠️ Email credentials not found in .env. Skipping email notification.")
        return

    subject = f"Invest Agent Analysis Report - {datetime.now().strftime('%Y-%m-%d')}"

    # Convert Markdown to HTML
    html_content = markdown.markdown(content, extensions=['tables', 'fenced_code', 'nl2br', 'sane_lists', 'toc'])

    # Basic CSS for better email rendering (Keep your original CSS)
    email_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 30px; }}
            h2 {{ color: #2980b9; margin-top: 25px; border-left: 4px solid #3498db; padding-left: 10px; }}
            h3 {{ color: #16a085; margin-top: 20px; }}
            p {{ margin-bottom: 15px; }}
            blockquote {{ border-left: 4px solid #ddd; padding: 10px 20px; color: #666; background: #f9f9f9; font-style: italic; margin: 20px 0; }}
            pre {{ background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; border: 1px solid #ddd; }}
            code {{ font-family: Consolas, Monaco, 'Andale Mono', monospace; background: #f4f4f4; padding: 2px 5px; border-radius: 3px; color: #d63384; }}
            ul, ol {{ margin-bottom: 15px; padding-left: 25px; }}
            li {{ margin-bottom: 5px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f8f9fa; color: #2c3e50; font-weight: bold; }}
            tr:nth-child(even) {{ background-color: #fcfcfc; }}
            hr {{ border: 0; border-top: 1px solid #eee; margin: 30px 0; }}
            .footer {{ font-size: 12px; color: #999; margin-top: 40px; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            .highlight {{ background-color: #fff3cd; padding: 2px 4px; border-radius: 4px; }}
        </style>
    </head>
    <body>
        {html_content}
        <div class="footer">
            Generated by <b>Gemini Invest Agent</b> • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart('alternative')
    msg['Subject'] = Header(subject, 'utf-8')
    msg['From'] = sender
    msg['To'] = receiver

    # Attach both plain text and HTML versions
    part1 = MIMEText(content, 'plain', 'utf-8')
    part2 = MIMEText(email_body, 'html', 'utf-8')

    msg.attach(part1)
    msg.attach(part2)

    # --- 重试逻辑开始 ---
    max_retries = 5  # 最大重试次数
    retry_interval = 5  # 初始重试间隔（秒）

    for attempt in range(1, max_retries + 1):
        try:
            print(f"🔄 [Attempt {attempt}/{max_retries}] 正在连接 SMTP 服务器...")

            # 显式设置超时，防止握手无限挂起
            socket.setdefaulttimeout(30)

            # 注意：context 创建放在循环里也是安全的，或者提出来也可以
            context = ssl.create_default_context()

            with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
                # server.set_debuglevel(1) # 如果需要看详细握手日志可开启，生产环境建议关闭保持清爽
                server.ehlo()
                server.starttls(context=context)  # TLS 握手
                server.ehlo()

                print(f"🔑 [Attempt {attempt}/{max_retries}] 正在验证身份...")
                server.login(sender, password)

                print(f"📨 [Attempt {attempt}/{max_retries}] 正在发送数据...")
                server.sendmail(sender, [receiver], msg.as_string())

            # 如果执行到这里没有报错，说明成功了
            print(f"✅ Email report successfully sent to {receiver}")
            return  # 成功后直接退出函数

        except (socket.timeout, smtplib.SMTPException, ConnectionError, OSError) as e:
            # 捕获常见的网络和协议错误
            print(f"❌ [Attempt {attempt}/{max_retries}] 发送失败: {e}")

            if attempt < max_retries:
                print(f"⏳ 等待 {retry_interval} 秒后进行下一次重试...")
                time.sleep(retry_interval)
                # 可选：指数退避，每次等待时间翻倍，避免拥塞
                # retry_interval *= 2
            else:
                print("⛔️ 已达到最大重试次数，放弃发送。")
                # 这里可以选择抛出异常，或者只是记录日志
                # raise e


if __name__ == "__main__":
    # Test call
    test_md = """
# Weekly Analysis
## Market Overview
The market is **bullish**.

- Apple: Up
- Google: Down

> "Buy low, sell high."
"""
    send_gmail_notification(test_md)
