import smtplib
import os
import socket

import ssl
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def send_gmail_notification(content: str):
    """
    Sends an email notification via Google SMTP.
    Requires EMAIL_SENDER and EMAIL_PASSWORD (App Password) in .env.
    """
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")  # Use Gmail App Password
    receiver = "longsizhuo@gmail.com"
    
    if not sender or not password:
        print("⚠️ Email credentials not found in .env. Skipping email notification.")
        return

    subject = f"Invest Agent Analysis Report - {datetime.now().strftime('%Y-%m-%d')}"
    
    # Convert Markdown to HTML
    html_content = markdown.markdown(content, extensions=['tables', 'fenced_code', 'nl2br', 'sane_lists', 'toc'])
    
    # Basic CSS for better email rendering
    email_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 30px; }}
            h2 {{ color: #2980b9; margin-top: 25px; border-left: 4px solid #3498db; padding-left: 10px; }}
            h3 {{ color: #16a085; margin-top: 20px; }}
            p {{ margin-bottom: 15px; }}
            blockquote {{ border-left: 4px solid #ddd; padding: 10px 20px; color: #666; background: #f9f9f9; font-style: italic; margin: 20px 0; }}
            pre {{ background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; border: 1px solid #ddd; }}
            code {{ font-family: Consolas, Monaco, 'Andale Mono', monospace; background: #f4f4f4; padding: 2px 5px; border-radius: 3px; color: #d63384; }}
            ul, ol {{ margin-bottom: 15px; padding-left: 25px; }}
            li {{ margin-bottom: 5px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f8f9fa; color: #2c3e50; font-weight: bold; }}
            tr:nth-child(even) {{ background-color: #fcfcfc; }}
            hr {{ border: 0; border-top: 1px solid #eee; margin: 30px 0; }}
            .footer {{ font-size: 12px; color: #999; margin-top: 40px; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            .highlight {{ background-color: #fff3cd; padding: 2px 4px; border-radius: 4px; }}
        </style>
    </head>
    <body>
        {html_content}
        <div class="footer">
            Generated by <b>Gemini Invest Agent</b> • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart('alternative')
    msg['Subject'] = Header(subject, 'utf-8')
    msg['From'] = sender
    msg['To'] = receiver

    # Attach both plain text and HTML versions
    part1 = MIMEText(content, 'plain', 'utf-8')
    part2 = MIMEText(email_body, 'html', 'utf-8')

    msg.attach(part1)
    msg.attach(part2)

    try:
        # Connect to Gmail's SMTP server

        socket.setdefaulttimeout(15)  # 全局 socket 超时（可选）

        with smtplib.SMTP("smtp.gmail.com", 587, timeout=15) as server:
            server.set_debuglevel(1)  # 打印 SMTP 交互日志
            server.ehlo()
            server.starttls(context=ssl.create_default_context())
            server.ehlo()
            server.login(sender, password)
            server.sendmail(sender, [receiver], msg.as_string())
        print(f"✅ Email report successfully sent to {receiver}")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    # Test call
    test_md = """
# Weekly Analysis
## Market Overview
The market is **bullish**.

- Apple: Up
- Google: Down

> "Buy low, sell high."
"""
    send_gmail_notification(test_md)
