import os
import smtplib
import socket
import ssl
import time  # 用于重试间隔
from datetime import datetime
from email.header import Header
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import markdown
from dotenv import load_dotenv

load_dotenv()


class EmailDeliveryError(RuntimeError):
    """邮件投递失败（重试耗尽）。

    在此之前 send_gmail_notification 重试 5 次后只 print 一行就 return，
    调用方（jobs/daily_report.py）拿不到任何信号，scheduler/runner 也无法
    记 status=failed —— 用户以为收到日报，实际上从未发出。改为重试耗尽
    时显式抛出本异常，让 scheduler runner 自动记入 job_runs 表，并允许
    上层做差异化处理（继续 job vs. 中断）。
    """


def _resolve_receiver(default_sender: str) -> str:
    """收件人优先级：memory/user.md 的 email 字段 → .env DIGEST_EMAIL_TO → 发件人自身"""
    try:
        from openinvest.core.memory_store import MemoryStore
        store = MemoryStore()
        user_doc = store.read("user")
        if user_doc:
            email = user_doc.get("email")
            if email:
                return str(email)
    except Exception:
        pass
    digest = os.getenv("DIGEST_EMAIL_TO")
    if digest:
        return digest
    return default_sender


# 邮件视觉设计（2026-06-20 重设计）：卡片式版式，主内容白底圆角卡，灰底衬托。
# 关键：分析师长文（CIO/Quant/Risk）走 .analyst 卡片（见 daily_report_builder），
# 用 md_in_html 扩展让卡片内部 markdown 仍被解析——粗体/换行正常，不再塞进灰色
# 代码块导致原文泄露。等宽数据块（黄金快照 / 摩擦成本表）才保留 <pre> monospace。
_DEFAULT_EMAIL_CSS = """
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, "PingFang SC", "Microsoft YaHei", sans-serif; line-height: 1.7; color: #2b2f36; background: #eef1f5; margin: 0; padding: 24px 12px; }
    .container { max-width: 720px; margin: 0 auto; background: #ffffff; border-radius: 12px; padding: 28px 34px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    h1 { font-size: 23px; color: #1a2533; margin: 4px 0 22px; padding-bottom: 14px; border-bottom: 3px solid #2d7ff9; }
    h2 { font-size: 19px; color: #1a2533; margin: 30px 0 12px; padding-left: 12px; border-left: 4px solid #2d7ff9; }
    h3 { font-size: 16px; color: #0b7285; margin: 22px 0 10px; }
    p { margin: 0 0 13px; }
    strong { color: #1a2533; }
    a { color: #2d7ff9; text-decoration: none; }
    blockquote { border-left: 4px solid #d7dee6; background: #f7f9fb; padding: 12px 18px; color: #52606d; margin: 18px 0; }
    ul, ol { margin: 0 0 14px; padding-left: 24px; }
    li { margin-bottom: 6px; }
    hr { border: 0; border-top: 1px solid #e4e9ee; margin: 26px 0; }
    table { border-collapse: collapse; width: 100%; margin: 18px 0; font-size: 14px; }
    th, td { border: 1px solid #e4e9ee; padding: 10px 12px; text-align: left; }
    th { background: #f4f6f8; color: #1a2533; font-weight: 600; }
    tr:nth-child(even) { background: #fafbfc; }
    /* 等宽数据块（对齐的快照/表格）才用 monospace */
    pre { background: #f7f9fb; border: 1px solid #e4e9ee; border-radius: 8px; padding: 14px 16px; overflow-x: auto; font-size: 13px; line-height: 1.5; }
    pre code { background: none; padding: 0; color: #2b2f36; }
    code { font-family: "SFMono-Regular", Consolas, Monaco, monospace; }
    :not(pre) > code { background: #eef1f5; padding: 2px 6px; border-radius: 4px; color: #c0392b; font-size: 13px; }
    /* 分析师卡片：LLM 长文走这里，正常排版而非灰色代码块 */
    .analyst { background: #f7f9fb; border: 1px solid #e7edf3; border-left: 4px solid #0b7285; border-radius: 8px; padding: 12px 18px; margin: 6px 0 18px; font-size: 14.5px; color: #3a444f; }
    .analyst p { margin: 0 0 9px; }
    .analyst p:last-child { margin-bottom: 0; }
    .footer { font-size: 12px; color: #9aa5b1; margin-top: 34px; padding-top: 18px; border-top: 1px solid #e4e9ee; text-align: center; }
    .highlight { background: #fff3cd; padding: 2px 5px; border-radius: 4px; }
"""


def render_markdown_email(content_md: str, *, footer_label: str = "Invest Agent") -> str:
    """Markdown → 完整 HTML body（含 CSS + footer），给 send_email_html 用。

    md_in_html 扩展：让 <div class="analyst" markdown="1"> 等 HTML 块内部的 markdown
    仍被解析（粗体/列表/换行正常）。这替代了旧的"把分析师长文塞进 ``` 代码块"做法
    —— 那会让 LLM 原文（含 **粗体** 标记）以灰色等宽块原样泄露、难以阅读。
    """
    html_content = markdown.markdown(
        content_md,
        extensions=['tables', 'fenced_code', 'nl2br', 'sane_lists', 'toc', 'md_in_html'],
    )
    return f"""
    <html>
    <head><meta charset="utf-8"><style>{_DEFAULT_EMAIL_CSS}</style></head>
    <body>
        <div class="container">
            {html_content}
            <div class="footer">
                Generated by <b>{footer_label}</b> • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </div>
        </div>
    </body>
    </html>
    """


def send_email_html(
    *,
    subject: str,
    html_body: str,
    plain_body: str,
    receiver: Optional[str] = None,
    max_retries: int = 5,
) -> str:
    """SMTP 退避发邮件 —— event_notifier 和 daily_report 共用。

    receiver 不传则按 _resolve_receiver 优先级解析。
    成功返回 receiver；凭据缺失返回 ""；重试耗尽抛 EmailDeliveryError。
    """
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    if not sender or not password:
        print("⚠️ Email credentials not found in .env. Skipping email notification.")
        return ""
    receiver = receiver or _resolve_receiver(default_sender=sender)

    msg = MIMEMultipart('alternative')
    msg['Subject'] = Header(subject, 'utf-8')
    msg['From'] = sender
    msg['To'] = receiver
    msg.attach(MIMEText(plain_body, 'plain', 'utf-8'))
    msg.attach(MIMEText(html_body, 'html', 'utf-8'))

    retry_interval = 5  # 5s → 10s → 20s → 40s → 80s
    last_exc: Exception | None = None
    for attempt in range(1, max_retries + 1):
        try:
            print(f"🔄 [Attempt {attempt}/{max_retries}] 正在连接 SMTP 服务器...")
            # 注：smtplib.SMTP timeout=30 已 cover per-call，不动 socket.setdefaulttimeout
            context = ssl.create_default_context()
            with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
                server.ehlo()
                server.starttls(context=context)
                server.ehlo()
                print(f"🔑 [Attempt {attempt}/{max_retries}] 正在验证身份...")
                server.login(sender, password)
                print(f"📨 [Attempt {attempt}/{max_retries}] 正在发送数据...")
                server.sendmail(sender, [receiver], msg.as_string())
            print(f"✅ Email successfully sent to {receiver}")
            return receiver
        except (socket.timeout, smtplib.SMTPException, ConnectionError, OSError) as e:
            last_exc = e
            print(f"❌ [Attempt {attempt}/{max_retries}] 发送失败: {e}")
            if attempt < max_retries:
                print(f"⏳ 等待 {retry_interval} 秒后进行下一次重试...")
                time.sleep(retry_interval)
                retry_interval *= 2

    print("⛔️ 已达到最大重试次数，放弃发送。")
    raise EmailDeliveryError(
        f"send_email_html 重试 {max_retries} 次后仍失败: "
        f"{type(last_exc).__name__}: {last_exc}"
    ) from last_exc


def send_gmail_notification(content: str) -> str:
    """通过 Gmail SMTP 发邮件（markdown 内容版本，给 daily_report 用）。

    成功：返回收件人地址。
    凭据缺失：返回空字符串（视为"故意 skip"，不算失败）。
    重试耗尽：抛 EmailDeliveryError —— 让 scheduler runner 记 job 状态为 failed。

    Receiver 优先级:
    1. memory/user.md 的 email 字段
    2. .env 的 DIGEST_EMAIL_TO
    3. 发件人本身
    """
    subject = f"Invest Agent Analysis Report - {datetime.now().strftime('%Y-%m-%d')}"
    html_body = render_markdown_email(content, footer_label="Gemini Invest Agent")
    return send_email_html(
        subject=subject,
        html_body=html_body,
        plain_body=content,
    )


if __name__ == "__main__":
    # Test call
    test_md = """
# Weekly Analysis
## Market Overview
The market is **bullish**.

- Apple: Up
- Google: Down

> "Buy low, sell high."
"""
    send_gmail_notification(test_md)
